---
abstract: 'Rule-based authorization mechanism'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  Data::Dumper: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Authorize-Rule
no_index:
  file:
    - README.pod
requires:
  List::Util: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/xsawyerx/authorize-rule/issues
  repository: http://github.com/xsawyerx/authorize-rule
version: 0.001
